version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: skilluser
      POSTGRES_PASSWORD: skillpass
      POSTGRES_DB: skilldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"


  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: skilluser
      DB_PASS: skillpass
      DB_NAME: skilldb
      REDIS_HOST: cache
    depends_on:
      - db
      - cache
      - search

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  pgdata:
